--- 
permalink: /:year/:month/:title
maruku: 
  png_dir: images/latex
  png_url: /images/latex
  use_tex: false
  use_divs: false
lsi: false
minutes: "    3430.5"
destination: ./_site
days: "       2.4"
markdown: maruku
exclude: 
- config
- CNAME
- Rakefile
- Capfile
- _site.tar.gz
- tomafro.net
pygments: true
pretty_style: html_extension
auto: true
server_port: 4000
